version: "3.7"

services:
  postgres:
    container_name: postgres
    image: 'postgres:15-alpine'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/data/postgres
    networks:
      - default

  api_v1:
    container_name: api_v1
    build:
      context: .
      dockerfile: Dockerfile
    command: "sh -c 'yarn start:dev'"
    networks:
      - default
    ports:
      - '3000:3000'
    volumes:
      - ./:/source
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}'
    restart: always

networks:
  default:

volumes:
  postgres: