version: "3.7"

services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/data/postgres
    networks:
      - default

  api_v1:
    container_name: api_v1
    image: 'node:16.16.0'
    networks:
      - default
    ports:
      - '3000:3000'
    command: sh -c "yarn install && yarn start:dev"
    working_dir: /source
    volumes:
      - ./:/source
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_NAME}'

networks:
  default:

volumes:
  postgres: