import { registerEnumType } from '@nestjs/graphql';

export enum EXCEPTION_CODES {
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  OUT_OF_RANGE = 'OUT_OF_RANGE',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_ENTRIES = 'INVALID_ENTRIES',
  PASSWORD_NOT_MATCH = 'PASSWORD_NOT_MATCH',
  UNAUTHORIZED_USER = 'UNAUTHORIZED_USER',
}

registerEnumType(EXCEPTION_CODES, { name: 'EXCEPTION_CODES' });
