export enum PERMISSIONS {
  CAN_CREATE_USER = 'CAN_CREATE_USER',
  CAN_GET_USERS = 'CAN_GET_USERS',
  CAN_GET_USER = 'CAN_GET_USER',
  CAN_DELETE_USER = 'CAN_DELETE_USER',
  CAN_UPDATE_USER = 'CAN_UPDATE_USER',
  CAN_UPLOAD_FILE = 'CAN_UPLOAD_FILE',
}
